In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler
from alphatest import backtest, util

data_path = r"C:\Users\qwane\Documents\git\alphatest\data\power"

at = backtest(data_path = data_path, daily_ticks=24, trading_fee = 0.05, compound=False)
cs = util.cross_sectional(valid_df=at.valid_df)

Backtesting parameters:
Annual days: 365.0, Daily ticks: 24
Trading fee (%): 5.0%
Risk free return (%): 3.0%
Data path: C:\Users\qwane\Documents\git\alphatest\data\power
Crypto benchmarks: ['BTC']
Stock benchmarks: ['VOO', 'GLD']

In [33]:
df_org = pd.read_csv('spread.csv').set_index('datetime', drop=True)
print(df_org.keys())
df_org

Index(['da_price', 'rt_price', 'spread', 'Biomass', 'Coal', 'Gas', 'Gas-CC',
       'Hydro', 'Nuclear', 'Other', 'Solar', 'Wind', 'WSL'],
      dtype='object')

,da_price,rt_price,spread,Biomass,Coal,Gas,Gas-CC,Hydro,Nuclear,Other,Solar,Wind,WSL
datetime,,,,,,,,,,,,,
2017-01-01 00:00:00-06:00,23.23,23.3575,0.1275,14.0784,4301.6835,216.4527,1012.4275,8.7413,1277.8774,0.8351,0.0000,536.1981,NaN
2017-01-01 01:00:00-06:00,21.82,21.4650,-0.3550,14.0859,4150.2643,215.2626,944.5370,8.7080,1277.8915,0.8251,0.0000,575.9067,NaN
2017-01-01 02:00:00-06:00,20.16,20.7350,0.5750,14.0773,3974.9419,214.3658,931.3578,8.6843,1277.9587,0.8232,0.0000,647.4909,NaN
2017-01-01 03:00:00-06:00,20.00,20.2700,0.2700,14.0850,3842.6835,214.5871,928.8150,8.6895,1277.9318,0.8213,0.0000,686.7596,NaN
2017-01-01 04:00:00-06:00,20.24,20.1200,-0.1200,14.0157,3783.5797,212.1251,989.8101,8.6354,1278.0895,0.7218,0.0000,688.6356,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 19:00:00-06:00,35.70,36.9375,1.2375,3.0507,2401.0343,741.2550,5425.3039,34.4903,1269.6854,188.1488,0.0003,1844.1436,-13.4305
2024-12-31 20:00:00-06:00,31.97,26.8275,-5.1425,3.0495,2351.5887,537.3593,5270.5980,29.1620,1269.6202,47.9010,0.0019,2230.9988,-66.2035
2024-12-31 21:00:00-06:00,25.64,22.5675,-3.0725,3.0519,2119.1500,420.9579,5132.5166,1.2520,1270.7105,13.7169,0.0001,2633.8813,-155.3025
2024-12-31 22:00:00-06:00,21.09,22.2300,1.1400,3.0540,1910.2811,331.0138,4841.2274,1.0288,1271.4680,10.5384,0.0001,2961.9563,-126.6053
2024-12-31 23:00:00-06:00,20.39,20.2875,-0.1025,3.0519,1841.7891,269.2101,4557.0868,1.0314,1271.4168,1.1056,0.0001,3273.3575,-206.8633

In [38]:
df = df_org.copy()
df.index = pd.to_datetime(df.index, utc=True)
df

,da_price,rt_price,spread,Biomass,Coal,Gas,Gas-CC,Hydro,Nuclear,Other,Solar,Wind,WSL
datetime,,,,,,,,,,,,,
2017-01-01 06:00:00+00:00,23.23,23.3575,0.1275,14.0784,4301.6835,216.4527,1012.4275,8.7413,1277.8774,0.8351,0.0000,536.1981,NaN
2017-01-01 07:00:00+00:00,21.82,21.4650,-0.3550,14.0859,4150.2643,215.2626,944.5370,8.7080,1277.8915,0.8251,0.0000,575.9067,NaN
2017-01-01 08:00:00+00:00,20.16,20.7350,0.5750,14.0773,3974.9419,214.3658,931.3578,8.6843,1277.9587,0.8232,0.0000,647.4909,NaN
2017-01-01 09:00:00+00:00,20.00,20.2700,0.2700,14.0850,3842.6835,214.5871,928.8150,8.6895,1277.9318,0.8213,0.0000,686.7596,NaN
2017-01-01 10:00:00+00:00,20.24,20.1200,-0.1200,14.0157,3783.5797,212.1251,989.8101,8.6354,1278.0895,0.7218,0.0000,688.6356,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-01 01:00:00+00:00,35.70,36.9375,1.2375,3.0507,2401.0343,741.2550,5425.3039,34.4903,1269.6854,188.1488,0.0003,1844.1436,-13.4305
2025-01-01 02:00:00+00:00,31.97,26.8275,-5.1425,3.0495,2351.5887,537.3593,5270.5980,29.1620,1269.6202,47.9010,0.0019,2230.9988,-66.2035
2025-01-01 03:00:00+00:00,25.64,22.5675,-3.0725,3.0519,2119.1500,420.9579,5132.5166,1.2520,1270.7105,13.7169,0.0001,2633.8813,-155.3025
2025-01-01 04:00:00+00:00,21.09,22.2300,1.1400,3.0540,1910.2811,331.0138,4841.2274,1.0288,1271.4680,10.5384,0.0001,2961.9563,-126.6053
2025-01-01 05:00:00+00:00,20.39,20.2875,-0.1025,3.0519,1841.7891,269.2101,4557.0868,1.0314,1271.4168,1.1056,0.0001,3273.3575,-206.8633

In [45]:
df_feature = pd.DataFrame(index=df_org.index)
df_feature

Empty DataFrame
Columns: []
Index: [2017-01-01 00:00:00-06:00, 2017-01-01 01:00:00-06:00, 2017-01-01 02:00:00-06:00, 2017-01-01 03:00:00-06:00, 2017-01-01 04:00:00-06:00, 2017-01-01 05:00:00-06:00, 2017-01-01 06:00:00-06:00, 2017-01-01 07:00:00-06:00, 2017-01-01 08:00:00-06:00, 2017-01-01 09:00:00-06:00, 2017-01-01 10:00:00-06:00, 2017-01-01 11:00:00-06:00, 2017-01-01 12:00:00-06:00, 2017-01-01 13:00:00-06:00, 2017-01-01 14:00:00-06:00, 2017-01-01 15:00:00-06:00, 2017-01-01 16:00:00-06:00, 2017-01-01 17:00:00-06:00, 2017-01-01 18:00:00-06:00, 2017-01-01 19:00:00-06:00, 2017-01-01 20:00:00-06:00, 2017-01-01 21:00:00-06:00, 2017-01-01 22:00:00-06:00, 2017-01-01 23:00:00-06:00, 2017-01-02 00:00:00-06:00, 2017-01-02 01:00:00-06:00, 2017-01-02 02:00:00-06:00, 2017-01-02 03:00:00-06:00, 2017-01-02 04:00:00-06:00, 2017-01-02 05:00:00-06:00, 2017-01-02 06:00:00-06:00, 2017-01-02 07:00:00-06:00, 2017-01-02 08:00:00-06:00, 2017-01-02 09:00:00-06:00, 2017-01-02 10:00:00-06:00, 2017-01-02 11:00:00-06:00, 2017-01-02 12:00:00-06:00, 2017-01-02 13:00:00-06:00, 2017-01-02 14:00:00-06:00, 2017-01-02 15:00:00-06:00, 2017-01-02 16:00:00-06:00, 2017-01-02 17:00:00-06:00, 2017-01-02 18:00:00-06:00, 2017-01-02 19:00:00-06:00, 2017-01-02 20:00:00-06:00, 2017-01-02 21:00:00-06:00, 2017-01-02 22:00:00-06:00, 2017-01-02 23:00:00-06:00, 2017-01-03 00:00:00-06:00, 2017-01-03 01:00:00-06:00, 2017-01-03 02:00:00-06:00, 2017-01-03 03:00:00-06:00, 2017-01-03 04:00:00-06:00, 2017-01-03 05:00:00-06:00, 2017-01-03 06:00:00-06:00, 2017-01-03 07:00:00-06:00, 2017-01-03 08:00:00-06:00, 2017-01-03 09:00:00-06:00, 2017-01-03 10:00:00-06:00, 2017-01-03 11:00:00-06:00, 2017-01-03 12:00:00-06:00, 2017-01-03 13:00:00-06:00, 2017-01-03 14:00:00-06:00, 2017-01-03 15:00:00-06:00, 2017-01-03 16:00:00-06:00, 2017-01-03 17:00:00-06:00, 2017-01-03 18:00:00-06:00, 2017-01-03 19:00:00-06:00, 2017-01-03 20:00:00-06:00, 2017-01-03 21:00:00-06:00, 2017-01-03 22:00:00-06:00, 2017-01-03 23:00:00-06:00, 2017-01-04 00:00:00-06:00, 2017-01-04 01:00:00-06:00, 2017-01-04 02:00:00-06:00, 2017-01-04 03:00:00-06:00, 2017-01-04 04:00:00-06:00, 2017-01-04 05:00:00-06:00, 2017-01-04 06:00:00-06:00, 2017-01-04 07:00:00-06:00, 2017-01-04 08:00:00-06:00, 2017-01-04 09:00:00-06:00, 2017-01-04 10:00:00-06:00, 2017-01-04 11:00:00-06:00, 2017-01-04 12:00:00-06:00, 2017-01-04 13:00:00-06:00, 2017-01-04 14:00:00-06:00, 2017-01-04 15:00:00-06:00, 2017-01-04 16:00:00-06:00, 2017-01-04 17:00:00-06:00, 2017-01-04 18:00:00-06:00, 2017-01-04 19:00:00-06:00, 2017-01-04 20:00:00-06:00, 2017-01-04 21:00:00-06:00, 2017-01-04 22:00:00-06:00, 2017-01-04 23:00:00-06:00, 2017-01-05 00:00:00-06:00, 2017-01-05 01:00:00-06:00, 2017-01-05 02:00:00-06:00, 2017-01-05 03:00:00-06:00, ...]

[70128 rows x 0 columns]

In [46]:
df_feature['month_sin'] = np.sin(2 * np.pi * (df.index.month - 1) / 12)
df_feature['dayofweek_sin'] = np.sin(2 * np.pi * df.index.dayofweek / 7)
df_feature['dayofmonth_sin'] = np.sin(2 * np.pi * (df.index.day - 1) / 31)
df_feature

                           month_sin  dayofweek_sin  dayofmonth_sin
datetime
2017-01-01 00:00:00-06:00        0.0      -0.781831             0.0
2017-01-01 01:00:00-06:00        0.0      -0.781831             0.0
2017-01-01 02:00:00-06:00        0.0      -0.781831             0.0
2017-01-01 03:00:00-06:00        0.0      -0.781831             0.0
2017-01-01 04:00:00-06:00        0.0      -0.781831             0.0
...                              ...            ...             ...
2024-12-31 19:00:00-06:00        0.0       0.974928             0.0
2024-12-31 20:00:00-06:00        0.0       0.974928             0.0
2024-12-31 21:00:00-06:00        0.0       0.974928             0.0
2024-12-31 22:00:00-06:00        0.0       0.974928             0.0
2024-12-31 23:00:00-06:00        0.0       0.974928             0.0

[70128 rows x 3 columns]

In [54]:
columns_for_iqr = ['da_price', 'rt_price', 'Biomass', 'Coal', 'Gas', 'Gas-CC',
       'Hydro', 'Nuclear', 'Other', 'Solar', 'Wind']
columns_to_scale = [c for c in df.columns if c in columns_for_iqr]
print("Columns to scale:", columns_to_scale)

scaler = RobustScaler()
df_feature[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])
df_feature[columns_to_scale] = df_feature[columns_to_scale].shift(24)
df_feature

Columns to scale: ['da_price', 'rt_price', 'Biomass', 'Coal', 'Gas', 'Gas-CC', 'Hydro', 'Nuclear', 'Other', 'Solar', 'Wind']

,month_sin,dayofweek_sin,dayofmonth_sin,Gas,Solar,Wind,da_price,rt_price,Biomass,Coal,Gas-CC,Hydro,Nuclear,Other
datetime,,,,,,,,,,,,,,
2017-01-01 00:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-01 01:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-01 02:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-01 03:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-01 04:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 19:00:00-06:00,0.0,0.974928,0.0,0.248407,-0.029210,0.311160,0.340732,0.297536,-0.852222,0.310431,0.178897,0.971900,0.079917,13.211848
2024-12-31 20:00:00-06:00,0.0,0.974928,0.0,-0.119629,-0.029212,0.594214,0.020396,-0.029077,-0.863046,0.018736,0.117841,0.710757,0.079454,7.699080
2024-12-31 21:00:00-06:00,0.0,0.974928,0.0,-0.296313,-0.029213,1.035159,-0.410918,-0.498148,-0.776369,-0.347762,-0.120605,-0.471542,0.084041,3.740959
2024-12-31 22:00:00-06:00,0.0,0.974928,0.0,-0.320606,-0.029213,1.293092,-0.405519,-0.599826,-0.775809,-0.543592,-0.413544,-0.510490,0.086498,4.301825
2024-12-31 23:00:00-06:00,0.0,0.974928,0.0,-0.377490,-0.029213,1.161147,-0.438512,-0.709733,-0.783212,-0.474613,-0.450252,-0.510422,0.085988,3.619022

In [56]:
df_feature['spread'] = df['spread']
df_feature.to_csv('spread_features.csv')
df_feature

,month_sin,dayofweek_sin,dayofmonth_sin,Gas,Solar,Wind,da_price,rt_price,Biomass,Coal,Gas-CC,Hydro,Nuclear,Other,spread
datetime,,,,,,,,,,,,,,,
2017-01-01 00:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1275
2017-01-01 01:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.3550
2017-01-01 02:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5750
2017-01-01 03:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2700
2017-01-01 04:00:00-06:00,0.0,-0.781831,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 19:00:00-06:00,0.0,0.974928,0.0,0.248407,-0.029210,0.311160,0.340732,0.297536,-0.852222,0.310431,0.178897,0.971900,0.079917,13.211848,1.2375
2024-12-31 20:00:00-06:00,0.0,0.974928,0.0,-0.119629,-0.029212,0.594214,0.020396,-0.029077,-0.863046,0.018736,0.117841,0.710757,0.079454,7.699080,-5.1425
2024-12-31 21:00:00-06:00,0.0,0.974928,0.0,-0.296313,-0.029213,1.035159,-0.410918,-0.498148,-0.776369,-0.347762,-0.120605,-0.471542,0.084041,3.740959,-3.0725
2024-12-31 22:00:00-06:00,0.0,0.974928,0.0,-0.320606,-0.029213,1.293092,-0.405519,-0.599826,-0.775809,-0.543592,-0.413544,-0.510490,0.086498,4.301825,1.1400
2024-12-31 23:00:00-06:00,0.0,0.974928,0.0,-0.377490,-0.029213,1.161147,-0.438512,-0.709733,-0.783212,-0.474613,-0.450252,-0.510422,0.085988,3.619022,-0.1025